// 1) STAMPARE NEL BROWERS UNA LISTA CHE CONTENGA ELEMENTI DI UN ARRAY.
//creare con vue un oggetto con all'interno un array

var root = new Vue({
    el: "#root",
    data: {
        
    },

    methods: {

    },
});







// 2) OGNI ELEMENTO HA UN ICONA 'X' ASSOCIATA (CREARE UNA FUNZIONE CHE PERMETTA ALLA X DI RIMUOVERE L'ELEMENTO DALLA LISTA).






// 3) PREDISPORRE UN INPUT (TEXT DOVE AGGIUNGERE DEL TESTO), SCRIVENDO NELL'JNPUT DEVE AGGIUNGERE CIO' CHE SI SCRIVE ALLA LISTA.







// 3) DIGITANDO UN TASTO INVIA SI AGGIUNGONO ALLA LISTA DOPO AVERLI SCRITTI NELL'INPUT.